export { default as LoginPage } from './LoginPage';
export { default as HomePage } from './HomePage';
export { default as MagnivaEvents } from './MagnivaEvents';
export { default as ThemePage } from './ThemePage';
export { default as InvitesPage } from './InvitesPage';
export { default as Attendees } from './AttendeesPage';
export { default as PaymentsPage } from './PaymentsPage';
export { default as SettingsPage } from './SettingPage';
export { default as UsersPage } from './UsersPage'
export { default as CustomersPage } from './CustomersPage';
export { default as BusinessSettings } from './BusinessSettings';
